# Generated by Django 2.2.14 on 2022-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bodypartdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('part', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
